#!/bin/bash

echo  -e "\n Renaming all the file having extension.txt:-" 
echo  -e "\n date and time"$(date) >> assignment.log
echo  -e "\n Rename:= "$(rename -v 's/^(.{2})/$1-new/' *.txt) >> assignment.log


